# Generated by Django 4.0.3 on 2022-03-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_project', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dir',
            field=models.TextField(default=819028),
        ),
    ]
