# Generated by Django 4.0.3 on 2022-03-13 23:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_listingcategory_listing_bid_listing_bid_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ListingCategory',
            new_name='Category',
        ),
    ]
