# Generated by Django 4.0.3 on 2022-03-15 15:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_listing_current_bid_alter_listing_starting_bid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='current_bid',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
    ]
