# Generated by Django 4.0.3 on 2022-03-15 21:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_listing_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='listing',
        ),
        migrations.AddField(
            model_name='listing',
            name='bids',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='listing', to='auctions.bid'),
            preserve_default=False,
        ),
    ]
