# Generated by Django 4.0.3 on 2022-03-15 23:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_remove_listing_bids_bid_listing'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='ending_time',
        ),
        migrations.AlterField(
            model_name='comment',
            name='listing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='auctions.listing'),
        ),
    ]
