# Generated by Django 4.0.3 on 2022-03-15 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_remove_listing_ending_time_alter_comment_listing'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='ending_time',
            field=models.DateTimeField(null=True),
        ),
    ]
